### PR TITLE
:sparkles: NEW: mono repo support

### LINKED ISSUE #536: Houdini 0.16 can't find runtime in monorepo - yarn workspaces
### Describe the bug

Maybe relevant to [this](https://github.com/HoudiniGraphql/houdini/blob/60ecb333a1396f9aa7244eac2f38741a58e7281f/src/common/config.ts#L300)

We have a turbo monorepo structure for our project and attempting to migrate to houdini 0.16 and the new sveltekit, houdini is unable to find the runtime.

```
<root>
node_modules/houdini/xxx
apps/mysveltekitapp/houdini.config.js
```

Our structure is like this, where node_modules are installed in the root but the app lives in a project within the monorepo.

When running `yarn workspace @project/mysveltekitapp houdini generate` it failes with:

```
❌ ENOENT: no such file or directory, stat '/app/apps/mysveltekitapp/node_modules/houdini/build/runtime-esm'
```

It should be looking in the monorepo root, where the runtime exists : `/app/node_modules/houdini/build/runtime-esm`

### Severity

blocking an upgrade

### Steps to Reproduce the Bug

1. Setup a sveltekit project in a monorepo using yarn workspaces
2. Follow houdini getting started guide
3. Error on `houdini generate` in yarn workspace.

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by jycouet**
Fixes #536

Looking up for `./node_modules/houdini`

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [ ] ~If applicable, add a test that would fail without this fix~
- [ ] ~Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`~
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

### CODE REVIEW

File: src/common/fs.ts [hunk 1]
```diff
@@ -113,6 +113,10 @@ export async function stat(filepath: string) {
 	return memfs.statSync(filepath)
 }
 
+export function isDirectorySync(dirPath: string) {
+	return fsExtra.existsSync(dirPath)
```
Comment (AlecAivazis) [inline src/common/fs.ts:117]: We should add something here to use the mock filesystem in tests

File: src/common/config.ts [hunk 2]
```diff
@@ -293,15 +293,43 @@ ${
 		return '$houdini.d.ts'
 	}
 
+	findNodeModulesHoudini(currentLocation: string) {
```
Comment (AlecAivazis) [inline src/common/config.ts:296]: I think having this as its own public method is a little dangerous since it opens the possibility that someone calls it directly instead of `runtimeSource` which would get around the check for `process.env.TEST`. I think we should either mark this as private or move its logic into `runtimeSource`.

**Review by AlecAivazis — CHANGES_REQUESTED** [review]
🎉

File: src/common/config.ts (hunk 2 above)
Comment (jycouet) [reply src/common/config.ts]: Like this?

File: src/common/fs.ts (hunk 1 above)
Comment (jycouet) [reply src/common/fs.ts]: I added the test, but nit sure about it.
Let me know 👍

Comment (AlecAivazis) [reply src/common/fs.ts]: nice! sorry, one last nitpick - can we call the function `existsSync` since it wraps that function in both scenarios?

Comment (jycouet) [reply src/common/fs.ts]: Yep, of course

**Review by AlecAivazis — APPROVED** [review]
