### PR TITLE
type definitions for loadAll

### LINKED ISSUE #658: Type error when using loadAll function.
### Describe the bug

There is a type error showing in VS Code when using the `loadAll` function. The full error code is:

```
Argument of type 'Promise<{ GetMainMenu: GetMainMenuStore; }>' is not assignable to parameter of type 'LoadAllInput'.
  Type 'Promise<{ GetMainMenu: GetMainMenuStore; }>' is not assignable to type 'LoadResult'.
    Type '{ GetMainMenu: GetMainMenuStore; }' is not assignable to type '{ [key: string]: QueryStore<any, {}, {}>; }'.
      Property 'GetMainMenu' is incompatible with index signature.
        Type 'GetMainMenuStore' is not assignable to type 'QueryStore<any, {}, {}>'.
          Types of property 'store' are incompatible.
            Type 'Writable<{ data: GetMainMenu$result | null; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: null; }>' is not assignable to type 'Writable<{ data: any; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: {}; }>'.
              Type '{ data: GetMainMenu$result | null; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: null; }' is not assignable to type '{ data: any; errors: { message: string; }[] | null; isFetching: boolean; partial: boolean; source: DataSource | null; variables: {}; }'.
                Types of property 'variables' are incompatible.
                  Type 'null' is not assignable to type '{}'.ts(2345)
```

As far as I can tell, I am using the function exactly as stated in the [Deep Dive: Loading multiple stores simultaneously](https://www.houdinigraphql.com/api/query#manual-loading) section of the docs. It seems to work as intended, just gives that dreaded red squiggly.

Additionally, types are not inferred/generated when using the `loadAll` function, so I'm currently having to use it as follows to get types working in the svelte page:

```typescript
...((await loadAll(
	load_GetMainMenu({ event }),
	load_GetCart({ event }),
	load_GetCurrentUser({ event }),
)) as unknown as {
	GetMainMenu: GetMainMenuStore
	GetCart: GetCartStore
	GetCurrentUser: GetCurrentUserStore
}),
```

### Severity

annoyance

### Steps to Reproduce the Bug

Add the loadAll function to a `+page.ts` or `+layout.ts` file.

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by AlecAivazis**
Fixes #658 

This PR contains more magic than all of pretty much all of houdini combined.... 

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

### CODE REVIEW

File: packages/houdini-svelte/src/runtime/index.ts [hunk 1]
```diff
@@ -8,6 +8,29 @@ export * from './session'
 type LoadResult = Promise<{ [key: string]: QueryStore<any, {}> }>
 type LoadAllInput = LoadResult | Record<string, LoadResult>
 
+// gets all the values from an object
```
Comment (AlecAivazis) [inline packages/houdini-svelte/src/runtime/index.ts:11]: @revnelson Do you mind adding this block to the `loadAll` definition in your generated runtime and confirming if it fixes the issue? It seems to work for me but It'd be nice for someone to confirm it

**Review by jycouet — APPROVED** [review]
