### PR TITLE
FIX: page/load BeforeLoadEvent types

### LINKED ISSUE #718: onError and beforeLoad cause issues due to relative imports.
### Describe the bug

Currently there is a minor bug that adds the type `[string: any]` to the `PageData` and `LayoutData` types if a beforeLoad is in a layout route. Didn't catch this due to minor mistake in test writing.

This will cause an error since if a BeforeLoadEvent for the layout references the PageLoadEvent, there is a circular dependency that typescript can't deal with. 

There is a similar case for AfterLoadEvent type however this isn't as serious.

I have a fix in the works but I just wanted to put it here in case anyone had a similar issue.

### Severity

annoyance

### Steps to Reproduce the Bug

1. basic project setup
2. beforeLoad using type beforeLoadEvent in +layout.ts in routes
3. generate types
4. `ERROR: typescript: 'beforeLoad' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

### Reproduction

_No response_

### PR DESCRIPTION
**Pull request by sjcobb2022**
Fixes #718

### To help everyone out, please make sure your PR does the following:

- [x] Update the first line to point to the ticket that this PR fixes
- [x] Add a message that clearly describes the fix
- [x] If applicable, add a test that would fail without this fix
- [x] Make sure the unit and integration tests pass locally with `pnpm run tests` and `cd integration && pnpm run tests`
- [x] Includes a changeset if your fix affects the user with `pnpm changeset`

This should fix things properly now. Sorry for the inconvenience this was a stupid oversight on my part.

### CODE REVIEW

File: packages/houdini-svelte/src/plugin/codegen/routes/index.ts [hunk 1]
```diff
@@ -324,7 +324,7 @@ function internal_append_afterLoad(queries: OperationDefinitionNode[]) {
 function append_beforeLoad(beforeLoad: boolean, type: 'Layout' | 'Page') {
 	return beforeLoad
 		? `
-export type BeforeLoadEvent = PageLoadEvent;
+export type BeforeLoadEvent = ${type}LoadEvent;
```
Comment (AlecAivazis) [inline packages/houdini-svelte/src/plugin/codegen/routes/index.ts:327]: Oh whoops! totally should have caught that myself. Anyway, thanks for fixing it 👍

**Review by AlecAivazis — APPROVED** [review]
